CREATE TABLE IF NOT EXISTS measurements (
    id INTEGER PRIMARY KEY,
    command TEXT NOT NULL,
    parameters TEXT NOT NULL,
    location TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
